---
- name: Create a temp directory to store files needed by the run
  tempfile:
    state: directory
    prefix: "flightdeck-cluster-"
  register: _certManager_tmp_dir
- name: Disable resource validation on namespace
  k8s:
    state: present
    definition: |
      apiVersion: v1
      kind: Namespace
      metadata:
        name: {{ flightdeck_cluster.namespace }}
        labels:
          certmanager.k8s.io/disable-validation: "true"
    kubeconfig: "{{ flightdeck_cluster_kubeconfig | default(omit) }}"
    namespace: "{{ flightdeck_cluster.namespace }}"
  when:
    - flightdeck_cluster.certManager.state | default('present') == 'present'
- name: Get the Cert manager manifest.
  get_url:
    url: "https://github.com/jetstack/cert-manager/releases/download/v0.12.0/cert-manager.yaml"
    dest: "{{ _certManager_tmp_dir.path }}/cert-manager.yaml"
- name: Apply the cert manager manifest.
  k8s:
    state: "{{ flightdeck_cluster.certManager.state | default('present') }}"
    src: "{{ _certManager_tmp_dir.path }}/cert-manager.yaml"
    kubeconfig: "{{ flightdeck_cluster_kubeconfig | default(omit) }}"
    namespace: "{{ flightdeck_cluster.namespace }}"
- name: delete temp items
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - "{{ _certManager_tmp_dir.path }}"
- name: Create cluster issuers for LetsEncyrpt
  k8s:
    state: "{{ item.state | default('present') }}"
    definition: |
      apiVersion: cert-manager.io/v1alpha2
      kind: ClusterIssuer
      metadata:
       name: "{{ item.name }}"
      spec:
       acme:
         server: "{{ item.server | default('https://acme-v02.api.letsencrypt.org/directory') }}"
         email: "{{ item.email }}"
         privateKeySecretRef:
           name: "{{ item.secret | default(item.name) }}"
         solvers:
           - http01:
               ingress:
                 class:  nginx
    kubeconfig: "{{ flightdeck_cluster_kubeconfig | default(omit) }}"
    namespace: "{{ flightdeck_cluster.namespace }}"
  loop: "{{ flightdeck_cluster.certManager.letsEncrypt | default([]) }}"
