---
- name: Create ingress
  k8s:
    state: "{{ flightdeck_cluster.ingress.state | default('present') }}"
    definition: |
      apiVersion: networking.k8s.io/v1beta1
      kind: Ingress
      metadata:
        name: "{{ flightdeck_cluster.ingress.name | default('ingress') }}"
        annotations:
          # GKE hosted clusters use the following:
          ingress.kubernetes.io/app-root: /
          ingress.kubernetes.io/affinity: cookie
          # Enable cores
          ingress.kubernetes.io/enable-cors: "true"
          nginx.ingress.kubernetes.io/enable-cors: "true"
          # Increase the file upload limit
          ingress.kubernetes.io/proxy-body-size: "{{ flightdeck_cluster.ingress.maxBodySize | default('128m') }}"
          nginx.ingress.kubernetes.io/proxy-body-size: "{{ flightdeck_cluster.ingress.maxBodySize | default('128m') }}"
          # Increase the proxy timeouts
          nginx.ingress.kubernetes.io/proxy-send-timeout: "{{ flightdeck_cluster.ingress.sendTimeout | default('300') }}"
          nginx.ingress.kubernetes.io/proxy-read-timeout: "{{ flightdeck_cluster.ingress.readTimeout | default('300') }}"
      {% if flightdeck_cluster.ingress.auth is defined %}
          nginx.ingress.kubernetes.io/auth-type: "{{ flightdeck_cluster.ingress.auth.type | default('basic') }}"
          nginx.ingress.kubernetes.io/auth-secret: "{{ flightdeck_cluster.ingress.auth.secret }}"
          nginx.ingress.kubernetes.io/auth-realm: "{{ flightdeck_cluster.ingress.auth.message | default('Please enter your login.') }}"
      {% endif %}
      {% if flightdeck_cluster.ingress.tlsIssuer is defined %}
          kubernetes.io/ingress.class: nginx
          cert-manager.io/cluster-issuer: {{ flightdeck_cluster.ingress.tlsIssuer }}
      {% endif %}
          nginx.ingress.kubernetes.io/use-regex: "{{ flightdeck_cluster.ingress.useRegex | default(true) | ternary('true', 'false') }}"
          nginx.ingress.kubernetes.io/proxy-buffer-size: "{{ flightdeck_cluster.ingress.proxyBufferSize | default('16k') }}"
      spec:
      {% if flightdeck_cluster.ingress.tls is defined %}
        tls:
      {% for _tls in flightdeck_cluster.ingress.tls %}
          - secretName: "{{ _tls.secret }}"
      {% if _tls.hosts is defined %}
            hosts:
      {% for _host in _tls.hosts %}
              - "{{ _host }}"
      {% endfor %}
      {% endif %}
      {% endfor %}
      {% endif %}
      {% if flightdeck_cluster.ingress.rules %}
        rules:
      {% for _rule in flightdeck_cluster.ingress.rules %}
          - host: "{{ _rule.host }}"
      {% if _rule.paths is defined %}
            http:
              paths:
      {% for _path in _rule.paths %}
                - path: "{{ _path.path | default('/') }}"
                  backend:
                    serviceName: "{{ _path.backend | default('web') }}"
                    servicePort: {{ _path.port | default('6081') }}
      {% endfor %}
      {% endif %}
      {% endfor %}
      {% endif %}
      {% if flightdeck_cluster.ingress.default is defined %}
        backend:
          serviceName: "{{ flightdeck_cluster.ingress.default.backend | default('web') }}"
          servicePort: {{ flightdeck_cluster.ingress.default.port | default('6081') }}
      {% endif %}
    kubeconfig: "{{ flightdeck_cluster_kubeconfig | default(omit) }}"
    namespace: "{{ flightdeck_cluster.namespace | default('default') }}"
