---
- name: Work with namespaces
  include_tasks: 'namespace.yml'
  when:
    - flightdeck_cluster.namespace is defined
    - flightdeck_cluster.namespace != 'default'
- name: Work with secrets
  include_tasks: 'secrets.yml'
- name: Work with configmaps
  include_tasks: 'configmaps.yml'
- name: Work with mysql
  include_tasks: 'mysql.yml'
  when:
    - flightdeck_cluster.mysql is defined
- name: Work with tractorbeam
  include_tasks: 'tractorbeam.yml'
  when:
    - flightdeck_cluster.tractorbeam is defined
- name: Work with memcache
  include_tasks: 'memcache.yml'
  when:
    - flightdeck_cluster.memcache is defined
- name: Work with solr
  include_tasks: 'solr.yml'
  when:
    - flightdeck_cluster.solr is defined
- name: Work with web
  include_tasks: 'web.yml'
  when:
    - flightdeck_cluster.web is defined
- name: Work with ingress controller
  include_tasks: 'ingressController.yml'
  when:
    - flightdeck_cluster.ingressController is defined
- name: Work with cert manager
  include_tasks: 'certManager.yml'
  when:
    - flightdeck_cluster.certManager is defined
- name: Work with ingress
  include_tasks: 'ingress.yml'
  when:
    - flightdeck_cluster.ingress is defined
- name: Work with cronjobs
  include_tasks: 'cron.yml'
  when:
    - flightdeck_cluster.cron is defined
