---
- name: Create memcache statefulset
  k8s:
    state: "{{ flightdeck_cluster.memcache.state | default('present') }}"
    definition: |
      apiVersion: apps/v1
      kind: StatefulSet
      metadata:
        name: memcache
      spec:
        selector:
          matchLabels:
            app: memcache
        serviceName: memcache
        replicas: {{ flightdeck_cluster.memcache.replicas | default('3') }}
        template:
          metadata:
            labels:
              app: memcache
          spec:
      {% if (flightdeck_cluster.memcache.nodeSelector is defined) and (flightdeck_cluster.memcache.nodeSelector.key is defined) and (flightdeck_cluster.memcache.nodeSelector.value is defined) %}
            nodeSelector:
              {{ flightdeck_cluster.memcache.nodeSelector.key }}: {{ flightdeck_cluster.memcache.nodeSelector.value }}
      {% endif %}
      {% if (flightdeck_cluster.memcache.affinity is defined) %}
            affinity:
              {{ flightdeck_cluster.memcache.affinity | to_nice_yaml(indent=2) | indent(8) }}
      {% endif %}
            containers:
              - image: "{{ flightdeck_cluster.memcache.image | default('memcached:1.6-alpine') }}"
                imagePullPolicy: Always
                name: "memcache"
      {% if (flightdeck_cluster.memcache.resources is defined) %}
                resources:
                  {{ flightdeck_cluster.memcache.resources | to_nice_yaml(indent=2) | indent(12) }}
      {% endif %}
      {% if flightdeck_cluster.memcache.memory is defined %}
                command:
                  - "memcached"
                  - "-m {{ flightdeck_cluster.memcache.memory | default(64) }}"
      {% endif %}
                ports:
                  - containerPort: 11211
                    name: memcache
                    protocol: TCP
    kubeconfig: "{{ flightdeck_cluster_kubeconfig | default(omit) }}"
    namespace: "{{ flightdeck_cluster.namespace | default('default') }}"
- name: Create memcache service
  k8s:
    state: "{{ flightdeck_cluster.memcache.state | default('present') }}"
    definition: |
      apiVersion: v1
      kind: Service
      metadata:
        name: memcache
      spec:
        clusterIP: None
        ports:
          - name: memcache
            port: 11211
            protocol: TCP
        selector:
          app: memcache
    kubeconfig: "{{ flightdeck_cluster_kubeconfig | default(omit) }}"
    namespace: "{{ flightdeck_cluster.namespace | default('default') }}"
