---
- name: Create namespace
  k8s:
    state: present
    definition: |
      apiVersion: v1
      kind: Namespace
      metadata:
        name: {{ flightdeck_cluster.namespace }}
    kubeconfig: "{{ flightdeck_cluster_kubeconfig | default(omit) }}"
    namespace: "{{ flightdeck_cluster.namespace }}"
