---
- name: Create secrets
  k8s:
    state: "{{ item.state | default('present') }}"
    definition: |
      apiVersion: v1
      kind: Secret
      metadata:
        name: {{ item.name }}
      type: {{ item.type | default('Opaque') }}
      {% if item.data is defined %}
      data:
      {% for _data in item.data %}
        {{ _data.name }}: {{ _data.value | string | b64encode }}
      {% endfor %}
      {% elif item.files is defined %}
      stringData:
      {% for _file in item.files %}
        {{ _file.name }}: {{ '|' }}
          {{ _file.content | string | indent(4) }}
      {% endfor %}
      {% endif %}
    kubeconfig: "{{ flightdeck_cluster_kubeconfig | default(omit) }}"
    namespace: "{{ flightdeck_cluster.namespace | default('default') }}"
  loop: "{{ flightdeck_cluster.secrets | default([]) }}"
  loop_control:
    label: "{{ item.name }}_{{ flightdeck_cluster.namespace | default('default') }}"
