---
- name: Create web deployment
  k8s:
    state: "{{ flightdeck_cluster.web.state | default('present') }}"
    definition: |
      apiVersion: extensions/v1beta1
      kind: Deployment
      metadata:
        labels:
          app: web
        name: web
      spec:
        replicas: {{ flightdeck_cluster.web.replicas | default('3') }}
        strategy:
          type: RollingUpdate
          rollingUpdate:
            maxSurge: 1
            maxUnavailable: 1
        minReadySeconds: 30
        template:
          metadata:
            labels:
              app: web
          spec:
      {% if (flightdeck_cluster.web.nodeSelector is defined) and (flightdeck_cluster.web.nodeSelector.key is defined) and (flightdeck_cluster.web.nodeSelector.value is defined) %}
            nodeSelector:
              {{ flightdeck_cluster.web.nodeSelector.key }}: {{ flightdeck_cluster.web.nodeSelector.value }}
      {% endif %}
            containers:
              - image: {{ flightdeck_cluster.web.image | default('ten7/flight-deck-web:latest') }}
                imagePullPolicy: Always
                name: web
                ports:
                  - containerPort: 80
      {% if (flightdeck_cluster.web.secrets is defined) or (flightdeck_cluster.web.configMaps is defined) %}
                volumeMounts:
      {% for _secret in flightdeck_cluster.web.secrets | default([]) %}
                  - name: "{{ _secret.volName | default('vol-secret-' + _secret.name) }}"
                    mountPath: "{{ _secret.path | default('/secrets') }}"
      {% endfor %}
      {% for _config in flightdeck_cluster.web.configMaps | default([]) %}
                  - name: "{{ _config.volName | default('vol-config-' + _config.name) }}"
                    mountPath: "{{ _config.path | default('/config') }}"
      {% endfor %}
      {% endif %}
              - image: {{ flightdeck_cluster.web.varnish.image | default('ten7/flight-deck-varnish') }}
                imagePullPolicy: Always
                name: varnish
                ports:
                  - name: "varnish-http"
                    containerPort: 6081
                    protocol: TCP
                  - name: "varnish-control"
                    containerPort: 6082
                    protocol: TCP
                env:
                  - name: "VARNISH_SECRET"
                    value: "{{ flightdeck_cluster.web.varnish.secret | default('secret') }}"
                  - name: "VARNISH_BACKEND_HOST"
                    value: "localhost"
                  - name: "VARNISH_BACKEND_PORT"
                    value: "80"
                  - name: "VARNISH_MEMORY_SIZE"
                    value: "{{ flightdeck_cluster.web.varnish.memory | default('256M') }}"
                  - name: "VARNISH_STORAGE_SIZE"
                    value: "{{ flightdeck_cluster.web.varnish.storage | default('1024M') }}"
      {% if flightdeck_cluster.web.imagePullSecrets is defined %}
            imagePullSecrets:
      {% for _imagePullSecret in flightdeck_cluster.web.imagePullSecrets %}
              - name: "{{ _imagePullSecret }}"
      {% endfor %}
      {% endif %}
      {% if (flightdeck_cluster.web.secrets is defined) or (flightdeck_cluster.web.configMaps is defined) %}
            volumes:
      {% for _secret in flightdeck_cluster.web.secrets | default([]) %}
              - name: "{{ _secret.volName | default('vol-secret-' + _secret.name) }}"
                secret:
                  secretName: "{{ _secret.name }}"
      {% endfor %}
      {% for _config in flightdeck_cluster.web.configMaps | default([]) %}
              - name: "{{ _config.volName | default('vol-config-' + _config.name) }}"
                configMap:
                  name: "{{ _config.name }}"
      {% endfor %}
      {% endif %}
    kubeconfig: "{{ flightdeck_cluster_kubeconfig | default(omit) }}"
    namespace: "{{ flightdeck_cluster.namespace | default('default') }}"
    wait: "{{ flightdeck_cluster.web.wait | default(false) }}"
    wait_condition:
      type: "Available"
      status: yes
      reason: "MinimumReplicasAvailable"
- name: Create web service
  k8s:
    state: "{{ flightdeck_cluster.web.state | default('present') }}"
    definition: |
      apiVersion: v1
      kind: Service
      metadata:
        name: web
      spec:
        ports:
          -
            name: http
            port: 80
            protocol: TCP
          -
            name: varnish
            port: 6081
        selector:
          app: web
    kubeconfig: "{{ flightdeck_cluster_kubeconfig | default(omit) }}"
    namespace: "{{ flightdeck_cluster.namespace | default('default') }}"
